apiVersion: v1
kind: Secret
metadata:
  name: kocc-auth
  namespace: ocp-monitoring-portal-test
type: Opaque
stringData:
  admin-username: admin
  admin-password: REPLACE_WITH_BOOTSTRAP_PASSWORD
  session-secret: REPLACE_WITH_RANDOM_SESSION_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: kocc-patch-api
  namespace: ocp-monitoring-portal-test
type: Opaque
stringData:
  api-token: REPLACE_WITH_PATCH_MASTER_API_TOKEN
